name: Build and publish fee-withdrawer-v2 image

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate build ID for Flux Image Automation
        id: tag
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: |
          echo "::set-output name=BUILD_ID::${GITHUB_REF#refs/*/}"

      - name: Generate build ID for Flux Image Automation
        id: build
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          sha=$(git rev-parse --short HEAD)
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${sha}-${ts}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        with:
          push: true
          tags: |
            "matterlabs/fee-withdrawer-v2:latest"
            "matterlabs/fee-withdrawer-v2:${{ steps.tag.outputs.BUILD_ID }}"
          file: Dockerfile
          no-cache: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        with:
          push: true
          tags: |
            "matterlabs/fee-withdrawer-v2:latest"
            "matterlabs/fee-withdrawer-v2:${{ steps.build.outputs.BUILD_ID }}"
          file: Dockerfile
          no-cache: true
